In [1]:
import numpy as np

In [11]:
v1 = np.arange(1,13).reshape(3,4)
v2 = np.arange(13,21).reshape(2,4)
print("v1: ", v1)
print("v2: ", v2)

v1:  [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
v2:  [[13 14 15 16]
 [17 18 19 20]]
